spring.application.name=api-java-ad
server.port=8080
server.servlet.context-path=/

# Conexao Active Directory LDAP
spring.ldap.urls=ldap://127.0.0.1:389
spring.ldap.base=dc=corp,dc=senai,dc=local
spring.ldap.username=cn=Administrator,cn=Users,dc=corp,dc=senai,dc=local
spring.ldap.password=${LDAP_PASSWORD:S3cur3P@ssw0rd!2026}
spring.ldap.embedded.validation.enabled=false

# Parametros da Organizacao
app.ldap.search-base=OU=SenaiCorp
app.ldap.default-user-ou=OU=Alunos,OU=Educacional,OU=SenaiCorp,DC=corp,DC=senai,DC=local
app.ldap.upn-domain=corp.senai.local
app.ldap.referral=ignore

# Seguranca API (HTTP Basic)
app.security.api-username=admin_api
app.security.api-password=${API_AUTH_PASSWORD:AdminSecret2026!}
app.security.api-role=ADMIN

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logs
logging.level.root=INFO
logging.level.com.senai.security.ad=DEBUG
